## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.

language: r
warnings_are_errors: true
sudo: true

r:
  - oldrel
  - release
  - devel

r_binary_packages:
  - rgdal
  - sp
  - rgeos
  - V8

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); coveralls()'
